# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -I. -Ivendor/hl2sdk-cs2/thirdparty/protobuf-3.21.8/src -Ivendor/hl2sdk-cs2/common -Ivendor/hl2sdk-cs2/game/shared -Ivendor/hl2sdk-cs2/game/server -Ivendor/hl2sdk-cs2/public -Ivendor/hl2sdk-cs2/public/engine -Ivendor/hl2sdk-cs2/public/mathlib -Ivendor/hl2sdk-cs2/public/tier0 -Ivendor/hl2sdk-cs2/public/tier1 -Ivendor/hl2sdk-cs2/public/entity2 -Ivendor/hl2sdk-cs2/public/game/server -Ivendor/hl2sdk-cs2/public/public/entity2 -Ivendor/metamod-source/core -Ivendor/metamod-source/core/sourcehook -Ibreakpad-config/linux -Ivendor/spdlog/include -Ivendor/funchook/include -Ivendor/breakpad/src -Ivendor/fmt/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_win64)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/AcceleratorCSS.so
OBJDIR = obj/win64/Debug
DEFINES += -DDEBUG -Dstricmp=strcasecmp -D_LINUX -DLINUX -DPOSIX -DGNUC -DCOMPILER_GCC -DPLATFORM_64BITS -D_GLIBCXX_USE_CXX11_ABI=0 -DMETA_IS_SOURCE2 -DHAVE_CONFIG_H -DHAVE_STDINT_H -D_ITERATOR_DEBUG_LEVEL=0 -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -fno-strict-aliasing -g -msse -Wno-register
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -fno-strict-aliasing -g -msse -std=c++2a -fvisibility=hidden -Wno-register
LIBS += build/breakpad/bin/win64/Debug/libbreakpad.a build/breakpad-client/bin/win64/Debug/libbreakpad-client.a build/libdisasm/bin/win64/Debug/liblibdisasm.a build/bin/win64/Debug/libspdlog.a -lpthread -lz -lfunchook
LDDEPS += build/breakpad/bin/win64/Debug/libbreakpad.a build/breakpad-client/bin/win64/Debug/libbreakpad-client.a build/libdisasm/bin/win64/Debug/liblibdisasm.a build/bin/win64/Debug/libspdlog.a
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/funchook/lib/Debug -Lvendor/hl2sdk-cs2/lib/linux64 -L/usr/lib64 -m64 -shared -Wl,-soname=AcceleratorCSS.so -l:libtier0.so -l:tier1.a -l:interfaces.a -l:mathlib.a -static-libstdc++ -static-libgcc

else ifeq ($(config),debug_linux64)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/AcceleratorCSS.so
OBJDIR = obj/linux64/Debug
DEFINES += -DDEBUG -Dstricmp=strcasecmp -D_LINUX -DLINUX -DPOSIX -DGNUC -DCOMPILER_GCC -DPLATFORM_64BITS -D_GLIBCXX_USE_CXX11_ABI=0 -DMETA_IS_SOURCE2 -DHAVE_CONFIG_H -DHAVE_STDINT_H -D_ITERATOR_DEBUG_LEVEL=0 -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -fPIC -fno-strict-aliasing -g -msse -Wno-register
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -fPIC -fno-strict-aliasing -g -msse -std=c++2a -fvisibility=hidden -Wno-register
LIBS += build/breakpad/bin/linux64/Debug/libbreakpad.a build/breakpad-client/bin/linux64/Debug/libbreakpad-client.a build/libdisasm/bin/linux64/Debug/liblibdisasm.a build/bin/linux64/Debug/libspdlog.a -lpthread -lz -lfunchook
LDDEPS += build/breakpad/bin/linux64/Debug/libbreakpad.a build/breakpad-client/bin/linux64/Debug/libbreakpad-client.a build/libdisasm/bin/linux64/Debug/liblibdisasm.a build/bin/linux64/Debug/libspdlog.a
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/funchook/lib/Debug -Lvendor/hl2sdk-cs2/lib/linux64 -shared -Wl,-soname=AcceleratorCSS.so -l:libtier0.so -l:tier1.a -l:interfaces.a -l:mathlib.a -static-libstdc++ -static-libgcc

else ifeq ($(config),release_win64)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/AcceleratorCSS.so
OBJDIR = obj/win64/Release
DEFINES += -DNDEBUG -Dstricmp=strcasecmp -D_LINUX -DLINUX -DPOSIX -DGNUC -DCOMPILER_GCC -DPLATFORM_64BITS -D_GLIBCXX_USE_CXX11_ABI=0 -DMETA_IS_SOURCE2 -DHAVE_CONFIG_H -DHAVE_STDINT_H -D_ITERATOR_DEBUG_LEVEL=0 -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -fno-strict-aliasing -msse -Wno-register
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -fno-strict-aliasing -msse -std=c++2a -fvisibility=hidden -Wno-register
LIBS += build/breakpad/bin/win64/Release/libbreakpad.a build/breakpad-client/bin/win64/Release/libbreakpad-client.a build/libdisasm/bin/win64/Release/liblibdisasm.a build/bin/win64/Release/libspdlog.a -lpthread -lz -lfunchook
LDDEPS += build/breakpad/bin/win64/Release/libbreakpad.a build/breakpad-client/bin/win64/Release/libbreakpad-client.a build/libdisasm/bin/win64/Release/liblibdisasm.a build/bin/win64/Release/libspdlog.a
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/funchook/lib/Release -Lvendor/hl2sdk-cs2/lib/linux64 -L/usr/lib64 -m64 -shared -Wl,-soname=AcceleratorCSS.so -s -l:libtier0.so -l:tier1.a -l:interfaces.a -l:mathlib.a -static-libstdc++ -static-libgcc

else ifeq ($(config),release_linux64)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/AcceleratorCSS.so
OBJDIR = obj/linux64/Release
DEFINES += -DNDEBUG -Dstricmp=strcasecmp -D_LINUX -DLINUX -DPOSIX -DGNUC -DCOMPILER_GCC -DPLATFORM_64BITS -D_GLIBCXX_USE_CXX11_ABI=0 -DMETA_IS_SOURCE2 -DHAVE_CONFIG_H -DHAVE_STDINT_H -D_ITERATOR_DEBUG_LEVEL=0 -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -fno-strict-aliasing -msse -Wno-register
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -fno-strict-aliasing -msse -std=c++2a -fvisibility=hidden -Wno-register
LIBS += build/breakpad/bin/linux64/Release/libbreakpad.a build/breakpad-client/bin/linux64/Release/libbreakpad-client.a build/libdisasm/bin/linux64/Release/liblibdisasm.a build/bin/linux64/Release/libspdlog.a -lpthread -lz -lfunchook
LDDEPS += build/breakpad/bin/linux64/Release/libbreakpad.a build/breakpad-client/bin/linux64/Release/libbreakpad-client.a build/libdisasm/bin/linux64/Release/liblibdisasm.a build/bin/linux64/Release/libspdlog.a
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/funchook/lib/Release -Lvendor/hl2sdk-cs2/lib/linux64 -shared -Wl,-soname=AcceleratorCSS.so -s -l:libtier0.so -l:tier1.a -l:interfaces.a -l:mathlib.a -static-libstdc++ -static-libgcc

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/breakpad_getcontext.o
GENERATED += $(OBJDIR)/bytereader.o
GENERATED += $(OBJDIR)/convar.o
GENERATED += $(OBJDIR)/crc32.o
GENERATED += $(OBJDIR)/dump_symbols.o
GENERATED += $(OBJDIR)/dwarf2diehandler.o
GENERATED += $(OBJDIR)/dwarf2reader.o
GENERATED += $(OBJDIR)/dwarf_cfi_to_module.o
GENERATED += $(OBJDIR)/dwarf_cu_to_module.o
GENERATED += $(OBJDIR)/dwarf_line_to_module.o
GENERATED += $(OBJDIR)/dwarf_range_list_handler.o
GENERATED += $(OBJDIR)/elf_reader.o
GENERATED += $(OBJDIR)/elf_symbols_to_module.o
GENERATED += $(OBJDIR)/entityidentity.o
GENERATED += $(OBJDIR)/entitysystem.o
GENERATED += $(OBJDIR)/extension.o
GENERATED += $(OBJDIR)/generichash.o
GENERATED += $(OBJDIR)/language.o
GENERATED += $(OBJDIR)/log.o
GENERATED += $(OBJDIR)/memoverride.o
GENERATED += $(OBJDIR)/module.o
GENERATED += $(OBJDIR)/path_helper.o
GENERATED += $(OBJDIR)/sourcehook.o
GENERATED += $(OBJDIR)/sourcehook_impl_chookidman.o
GENERATED += $(OBJDIR)/sourcehook_impl_chookmaninfo.o
GENERATED += $(OBJDIR)/sourcehook_impl_cproto.o
GENERATED += $(OBJDIR)/sourcehook_impl_cvfnptr.o
GENERATED += $(OBJDIR)/stabs_reader.o
GENERATED += $(OBJDIR)/stabs_to_module.o
OBJECTS += $(OBJDIR)/breakpad_getcontext.o
OBJECTS += $(OBJDIR)/bytereader.o
OBJECTS += $(OBJDIR)/convar.o
OBJECTS += $(OBJDIR)/crc32.o
OBJECTS += $(OBJDIR)/dump_symbols.o
OBJECTS += $(OBJDIR)/dwarf2diehandler.o
OBJECTS += $(OBJDIR)/dwarf2reader.o
OBJECTS += $(OBJDIR)/dwarf_cfi_to_module.o
OBJECTS += $(OBJDIR)/dwarf_cu_to_module.o
OBJECTS += $(OBJDIR)/dwarf_line_to_module.o
OBJECTS += $(OBJDIR)/dwarf_range_list_handler.o
OBJECTS += $(OBJDIR)/elf_reader.o
OBJECTS += $(OBJDIR)/elf_symbols_to_module.o
OBJECTS += $(OBJDIR)/entityidentity.o
OBJECTS += $(OBJDIR)/entitysystem.o
OBJECTS += $(OBJDIR)/extension.o
OBJECTS += $(OBJDIR)/generichash.o
OBJECTS += $(OBJDIR)/language.o
OBJECTS += $(OBJDIR)/log.o
OBJECTS += $(OBJDIR)/memoverride.o
OBJECTS += $(OBJDIR)/module.o
OBJECTS += $(OBJDIR)/path_helper.o
OBJECTS += $(OBJDIR)/sourcehook.o
OBJECTS += $(OBJDIR)/sourcehook_impl_chookidman.o
OBJECTS += $(OBJDIR)/sourcehook_impl_chookmaninfo.o
OBJECTS += $(OBJDIR)/sourcehook_impl_cproto.o
OBJECTS += $(OBJDIR)/sourcehook_impl_cvfnptr.o
OBJECTS += $(OBJDIR)/stabs_reader.o
OBJECTS += $(OBJDIR)/stabs_to_module.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking AcceleratorCSS
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning AcceleratorCSS
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/extension.o: src/extension.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/log.o: src/log.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/entityidentity.o: vendor/hl2sdk-cs2/entity2/entityidentity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/entitysystem.o: vendor/hl2sdk-cs2/entity2/entitysystem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/memoverride.o: vendor/hl2sdk-cs2/public/tier0/memoverride.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/convar.o: vendor/hl2sdk-cs2/tier1/convar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/generichash.o: vendor/hl2sdk-cs2/tier1/generichash.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook.o: vendor/metamod-source/core/sourcehook/sourcehook.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_impl_chookidman.o: vendor/metamod-source/core/sourcehook/sourcehook_impl_chookidman.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_impl_chookmaninfo.o: vendor/metamod-source/core/sourcehook/sourcehook_impl_chookmaninfo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_impl_cproto.o: vendor/metamod-source/core/sourcehook/sourcehook_impl_cproto.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_impl_cvfnptr.o: vendor/metamod-source/core/sourcehook/sourcehook_impl_cvfnptr.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/bytereader.o: vendor/breakpad/src/common/dwarf/bytereader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dwarf2diehandler.o: vendor/breakpad/src/common/dwarf/dwarf2diehandler.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dwarf2reader.o: vendor/breakpad/src/common/dwarf/dwarf2reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/elf_reader.o: vendor/breakpad/src/common/dwarf/elf_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dwarf_cfi_to_module.o: vendor/breakpad/src/common/dwarf_cfi_to_module.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dwarf_cu_to_module.o: vendor/breakpad/src/common/dwarf_cu_to_module.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dwarf_line_to_module.o: vendor/breakpad/src/common/dwarf_line_to_module.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dwarf_range_list_handler.o: vendor/breakpad/src/common/dwarf_range_list_handler.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/language.o: vendor/breakpad/src/common/language.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/breakpad_getcontext.o: vendor/breakpad/src/common/linux/breakpad_getcontext.S
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crc32.o: vendor/breakpad/src/common/linux/crc32.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dump_symbols.o: vendor/breakpad/src/common/linux/dump_symbols.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/elf_symbols_to_module.o: vendor/breakpad/src/common/linux/elf_symbols_to_module.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/module.o: vendor/breakpad/src/common/module.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/path_helper.o: vendor/breakpad/src/common/path_helper.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stabs_reader.o: vendor/breakpad/src/common/stabs_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stabs_to_module.o: vendor/breakpad/src/common/stabs_to_module.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif